### ISSUE TITLE
Missing package: Scales

### ISSUE THREAD

**Issue by mgkahn** [ohdsi-studies/ReproducibilityRayJAMA2021#2]
Using commit d78713fb from 5-Jul-2022 that incorporates CohortDiagnostics 3.0.2 with BG fix, get the following error running CohortDiagnostics::executDiagnostics()

Executing SQL took 15.9 secs
Computing incidence rates took 24.5 secs
  Computing incidence rate for cohort 'Ray JAMA 2021-O bleeding-related hospitalizations'
Calculating incidence rate per year by age and gender
  |===========================================================================================| 100%
Executing SQL took 16.7 secs
Computing incidence rates took 25.3 secs
  Computing incidence rate for cohort 'Ray JAMA 2021_O Ischemic Stroke '
Calculating incidence rate per year by age and gender
  |===========================================================================================| 100%
Executing SQL took 17.1 secs
Computing incidence rates took 26.5 secs
  Computing incidence rate for cohort 'ray jama 2022_O Hemorrhagic Stroke'
Calculating incidence rate per year by age and gender
  |===========================================================================================| 100%
Executing SQL took 16.6 secs
Computing incidence rates took 25.3 secs
- Censoring 313 values (1.7%) from cohortCount because value below minimum                           
- Censoring 5551 values (30.4%) from personYears because value below minimum
- Censoring 307 values (1.7%) from incidenceRate because value below minimum
Running Incidence Rate took 2.99 mins                                                              
Computing Cohort Relationship
Error in loadNamespace(x) : there is no package called ‘scales’
>

**Comment by mdlavallee92** [comment]
added all package dependencies for Cohort Diagnostics to the lock file. please download the new version of the repos
